name: Build CMake project

on:
  workflow_dispatch:

jobs:
  build:
    name: Build for Windows x64 MSVC
    runs-on: windows-latest
    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows-static-md
      VCPKG_DEFAULT_HOST_TRIPLET: x64-windows-static-md

    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{ github.workspace }}/misc/vcpkg
          runVcpkgInstall: true

      - name: Set up MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: CMake Configure
        run: |
          cmake --preset release

      - name: CMake Build
        run: |
          cmake --build build
