name: Build CMake project

on:
  workflow_dispatch:

jobs:
  build:
    name: Build for Windows x64 MSVC
    runs-on: windows-latest

    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache vcpkg
        uses: actions/cache@v4
        with:
          path: |
            misc/vcpkg/installed
            misc/vcpkg/packages
          key: vcpkg-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('vcpkg.json', '.git/modules/misc/vcpkg/HEAD') }}
          restore-keys: |
           vcpkg-${{ runner.os }}-${{ runner.arch }}-

      - name: Set up MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: CMake Configure
        run: |
          cmake --preset release

      - name: CMake Build
        run: |
          cmake --build build
