name: Build CMake project

on:
  workflow_dispatch:

env:
  VCPKG_FEATURE_FLAGS: binarycaching
  VCPKG_BINARY_SOURCES: "clear;files,readwrite"

jobs:
  build:
    name: Build for Windows x64 MSVC
    runs-on: windows-latest

    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache vcpkg dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            misc/vcpkg/installed
            misc/vcpkg/packages
            misc/vcpkg/buildtrees/**/installed
            misc/vcpkg/buildtrees/**/status*
            !misc/vcpkg/buildtrees/**/src
            !misc/vcpkg/buildtrees/**/obj-*
          key: vcpkg-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('vcpkg.json', '.git/modules/misc/vcpkg/HEAD') }}
          restore-keys: |
           vcpkg-${{ runner.os }}-${{ runner.arch }}-

      - name: Cache vcpkg archives
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        with:
          path: ~\\AppData\\Local\\vcpkg\\archives
          key: vcpkg-archives-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('vcpkg.json', '.git/modules/misc/vcpkg/HEAD') }}
          restore-keys: |
            vcpkg-archives-${{ runner.os }}-${{ runner.arch }}-

      - name: Set up MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: CMake Configure
        run: |
          cmake --preset release

      - name: CMake Build
        run: |
          cmake --build build
